import * as monaco from 'monaco-editor';

export const defineMonacoThemes = (monacoInstance: typeof monaco) => {
  // 1. Ocal Signature Theme (Sleek Dark, Emerald/Lime/Cyan Accents, Layered Surfaces)
  monacoInstance.editor.defineTheme('ocal-signature', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'E8E8E8', background: '0C0C0C' },
      { token: 'keyword', foreground: '38BDF8', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: '818CF8', fontStyle: 'bold' },
      { token: 'type', foreground: '34D058', fontStyle: 'bold' },
      { token: 'type.identifier', foreground: '2DD4BF' },
      { token: 'string', foreground: 'A3E635' },
      { token: 'string.escape', foreground: 'E8FF47' },
      { token: 'comment', foreground: '64748B', fontStyle: 'italic' },
      { token: 'number', foreground: 'FB923C' },
      { token: 'preprocessor', foreground: 'E8FF47', fontStyle: 'bold' },
      { token: 'delimiter', foreground: '94A3B8' },
      { token: 'operator', foreground: '38BDF8' },
      { token: 'identifier', foreground: 'F1F5F9' },
      { token: 'function', foreground: '60CDFF', fontStyle: 'bold' },
    ],
    colors: {
      'editor.background': '#0C0C0C',
      'editor.foreground': '#E8E8E8',
      'editorCursor.foreground': '#34D058',
      'editor.lineHighlightBackground': '#14151C',
      'editorLineNumber.foreground': '#4B5563',
      'editorLineNumber.activeForeground': '#34D058',
      'editor.selectionBackground': '#34D05830',
      'editor.inactiveSelectionBackground': '#34D05818',
      'editorGutter.background': '#0C0C0C',
      'editorWidget.background': '#121318',
      'editorWidget.border': '#252536',
      'minimap.background': '#0C0C0C',
      'minimapSlider.background': '#34D05815',
      'minimapSlider.hoverBackground': '#34D05828',
      'minimapSlider.activeBackground': '#34D05840',
      'minimap.errorHighlight': '#F43F5E',
      'minimap.warningHighlight': '#F59E0B',
      'scrollbarSlider.background': '#25253688',
      'scrollbarSlider.hoverBackground': '#34D05855',
      'scrollbarSlider.activeBackground': '#34D05899',
    },
  });
  // 1. Professional Dark+ Theme (Visual Studio / WinUI Fluent)
  monacoInstance.editor.defineTheme('modern-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'D4D4D4', background: '1E1E1E' },
      { token: 'keyword', foreground: '569CD6', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: 'C586C0', fontStyle: 'bold' },
      { token: 'type', foreground: '4EC9B0', fontStyle: 'bold' },
      { token: 'type.identifier', foreground: '4EC9B0' },
      { token: 'string', foreground: 'CE9178' },
      { token: 'string.escape', foreground: 'D7BA7D' },
      { token: 'comment', foreground: '6A9955', fontStyle: 'italic' },
      { token: 'number', foreground: 'B5CEA8' },
      { token: 'preprocessor', foreground: '9CDCFE', fontStyle: 'bold' },
      { token: 'delimiter', foreground: 'D4D4D4' },
      { token: 'operator', foreground: 'D4D4D4' },
      { token: 'identifier', foreground: '9CDCFE' },
    ],
    colors: {
      'editor.background': '#1E1E1E',
      'editor.foreground': '#D4D4D4',
      'editorCursor.foreground': '#AEAFAD',
      'editor.lineHighlightBackground': '#282828',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#C6C6C6',
      'editor.selectionBackground': '#264F78',
      'editor.inactiveSelectionBackground': '#3A3D41',
      'editorGutter.background': '#1E1E1E',
      'editorWidget.background': '#252526',
      'editorWidget.border': '#454545',
      // Minimap preview styling
      'minimap.background': '#1E1E1E',
      'minimapSlider.background': '#FFFFFF15',
      'minimapSlider.hoverBackground': '#FFFFFF25',
      'minimapSlider.activeBackground': '#FFFFFF35',
      'minimap.errorHighlight': '#F14C4C',
      'minimap.warningHighlight': '#CCA700',
      // Sleek scrollbar styling
      'scrollbarSlider.background': '#42424260',
      'scrollbarSlider.hoverBackground': '#55555590',
      'scrollbarSlider.activeBackground': '#777777BB',
    },
  });

  // 2. Classic Turbo C++ DOS Nostalgia Theme
  monacoInstance.editor.defineTheme('turbo-nostalgia', {
    base: 'vs-dark',
    inherit: false,
    rules: [
      { token: '', foreground: 'FFFFFF', background: '0000AA' },
      { token: 'keyword', foreground: 'FFFF55', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: 'FFFF55', fontStyle: 'bold' },
      { token: 'type', foreground: 'FFFFFF', fontStyle: 'bold' },
      { token: 'type.identifier', foreground: 'FFFFFF' },
      { token: 'string', foreground: '55FFFF' },
      { token: 'string.escape', foreground: '55FF55' },
      { token: 'comment', foreground: 'AAAAAA', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: 'AAAAAA' },
      { token: 'number', foreground: '55FF55' },
      { token: 'delimiter', foreground: 'FFFFFF' },
      { token: 'operator', foreground: 'FFFFFF' },
      { token: 'identifier', foreground: 'FFFFFF' },
      { token: 'preprocessor', foreground: '55FFFF', fontStyle: 'bold' },
      { token: 'tag', foreground: 'FFFF55' },
    ],
    colors: {
      'editor.background': '#0000AA',
      'editor.foreground': '#FFFFFF',
      'editorCursor.foreground': '#FFFF55',
      'editor.lineHighlightBackground': '#000088',
      'editorLineNumber.foreground': '#55FFFF',
      'editorLineNumber.activeForeground': '#FFFF55',
      'editor.selectionBackground': '#0055AA',
      'editor.inactiveSelectionBackground': '#003377',
      'editorGutter.background': '#0000AA',
      'editorWidget.background': '#000088',
      'editorWidget.border': '#55FFFF',
      'minimap.background': '#000088',
      'minimapSlider.background': '#FFFF5533',
      'minimapSlider.hoverBackground': '#FFFF5566',
      'minimapSlider.activeBackground': '#FFFF5599',
      'scrollbarSlider.background': '#0055AA88',
      'scrollbarSlider.hoverBackground': '#55FFFF88',
      'scrollbarSlider.activeBackground': '#FFFF55CC',
    },
  });

  // 3. Cyberpunk Neon Theme
  monacoInstance.editor.defineTheme('cyberpunk-neon', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'F1F5F9', background: '0D081A' },
      { token: 'keyword', foreground: 'FF2A85', fontStyle: 'bold' },
      { token: 'type', foreground: '05D9E8' },
      { token: 'string', foreground: 'FFE600' },
      { token: 'comment', foreground: '7158E2', fontStyle: 'italic' },
      { token: 'number', foreground: '00FF9F' },
      { token: 'preprocessor', foreground: 'FF6B6B' },
    ],
    colors: {
      'editor.background': '#0D081A',
      'editor.foreground': '#F1F5F9',
      'editorCursor.foreground': '#05D9E8',
      'editor.lineHighlightBackground': '#24144255',
      'editorLineNumber.foreground': '#7158E2',
      'editorLineNumber.activeForeground': '#05D9E8',
      'editor.selectionBackground': '#FF2A8544',
      'editorGutter.background': '#0D081A',
      'minimap.background': '#0D081A',
      'minimapSlider.background': '#FF2A8533',
      'minimapSlider.hoverBackground': '#FF2A8566',
      'minimapSlider.activeBackground': '#FF2A8599',
      'scrollbarSlider.background': '#7158E255',
      'scrollbarSlider.hoverBackground': '#05D9E888',
      'scrollbarSlider.activeBackground': '#FF2A85CC',
    },
  });
};
